---
- hosts: webservers
  name: webservers provisioning
  remote_user: root
  become: yes
  vars:
    http_port: 80
    doc_dir: /ansible/
    doc_root: /var/www/html/ansible/
    username: geniousphp
  tasks:
    - name: Ensure Apache is installed
      yum: name=httpd state=present
      when: ansible_os_family == "RedHat"

    - name: Start Apache
      service: name=httpd enabled=yes state=started


    - name: Deploy configuration file
      template: src=templates/httpd.j2 dest=/etc/httpd/conf/httpd.conf
      notify:
        - reload apache

    - name: Create root directory
      file:
        path: "{{doc_root}}"
        state: directory
        recurse: yes
    
    - name: Copy Site Files
      template: src=templates/index.j2 dest={{ doc_root }}/index.html

  handlers:
    - name: reload apache
      service: name=httpd state=restarted

- hosts: dbservers
  name: dbservers provisioning
  remote_user: root
  become: yes
  tasks:
    - name: Ensure Mysql is installed
      yum: name=mysql-server state=present
      when: ansible_os_family == "RedHat"

    - name: Start Mysql
      service: name=mysqld enabled=yes state=started

- hosts: webservers:dbservers
  remote_user: root
  become: yes
  tasks:
    - name: Stop IPTABLES
      service: name=iptables state=stopped

