---
- name: Ensure Apache is installed
  yum: name=httpd state=present
  when: ansible_os_family == "RedHat"

- name: Start Apache
  service: name=httpd enabled=yes state=started


- name: Deploy configuration file
  template: src=httpd.j2 dest=/etc/httpd/conf/httpd.conf
  notify:
    - reload apache

- name: Create root directory
  file:
    path: "{{doc_root}}"
    state: directory
    recurse: yes

- name: Copy Site Files
  template: src=index.j2 dest={{ doc_root }}/index.html